repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
    - id: no-commit-to-branch
      args: ['--branch', 'master']
- repo: https://github.com/AlogluMustafaCan/custom-git-hook
  rev: 9edf872
  hooks:
    - commitizen
    - refs_control
    - type_control
